// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTyJ3E58GcJwpPI8vYA-2KYT2dX6NCbJU',
    appId: '1:199712909810:web:7f1ffff5ab68e84f87a36b',
    messagingSenderId: '199712909810',
    projectId: 'finance-track-82326',
    authDomain: 'finance-track-82326.firebaseapp.com',
    storageBucket: 'finance-track-82326.firebasestorage.app',
    measurementId: 'G-882YR9ER3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpn0GH7IU1QtuPbIWwnCtxFLh0_IavYa4',
    appId: '1:199712909810:android:32436678ae7bde6587a36b',
    messagingSenderId: '199712909810',
    projectId: 'finance-track-82326',
    storageBucket: 'finance-track-82326.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJjO6S-iiQ9ma50YNKrZ1u8kHERRxtzM',
    appId: '1:199712909810:ios:3a3abd6d9b6bca3c87a36b',
    messagingSenderId: '199712909810',
    projectId: 'finance-track-82326',
    storageBucket: 'finance-track-82326.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJjO6S-iiQ9ma50YNKrZ1u8kHERRxtzM',
    appId: '1:199712909810:ios:3a3abd6d9b6bca3c87a36b',
    messagingSenderId: '199712909810',
    projectId: 'finance-track-82326',
    storageBucket: 'finance-track-82326.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBTyJ3E58GcJwpPI8vYA-2KYT2dX6NCbJU',
    appId: '1:199712909810:web:7f1ffff5ab68e84f87a36b',
    messagingSenderId: '199712909810',
    projectId: 'finance-track-82326',
    authDomain: 'finance-track-82326.firebaseapp.com',
    storageBucket: 'finance-track-82326.firebasestorage.app',
    measurementId: 'G-882YR9ER3H',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTyJ3E58GcJwpPI8vYA-2KYT2dX6NCbJU',
    appId: '1:199712909810:web:7a17d34669c3cdd987a36b',
    messagingSenderId: '199712909810',
    projectId: 'finance-track-82326',
    authDomain: 'finance-track-82326.firebaseapp.com',
    storageBucket: 'finance-track-82326.firebasestorage.app',
    measurementId: 'G-LR7T5PG1M9',
  );
}
